name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build docker
      run: docker build --tag=cross/esp8266 .
    - name: build firmware
      run: docker run -v "$(pwd)"/src/:/home/sdkbuilder/esp-homekit/src cross/esp8266
